# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cms-lite}
  s.version = "3.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Ball"]
  s.date = %q{2010-09-14}
  s.description = %q{CMS gem that makes it simple to interact with your content developers by serving pages from '/content'.}
  s.email = %q{justinball@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gemspec",
     ".gitignore",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/controllers/cms_lite_controller.rb",
     "cms-lite.gemspec",
     "config/routes.rb",
     "lib/cms_lite.rb",
     "lib/cms_lite/config.rb",
     "lib/cms_lite/engine.rb",
     "lib/cms_lite/exceptions.rb",
     "lib/cms_lite/languages.rb",
     "lib/cms_lite/resolver.rb",
     "lib/tasks/cms_lite.rake",
     "test/rails_test/.gitignore",
     "test/rails_test/.rake_tasks",
     "test/rails_test/Gemfile",
     "test/rails_test/Gemfile.lock",
     "test/rails_test/Rakefile",
     "test/rails_test/app/controllers/application_controller.rb",
     "test/rails_test/app/models/.keep",
     "test/rails_test/app/models/user.rb",
     "test/rails_test/app/models/user_session.rb",
     "test/rails_test/app/views/layouts/default.html.erb",
     "test/rails_test/app/views/layouts/test.html.erb",
     "test/rails_test/config.ru",
     "test/rails_test/config/application.rb",
     "test/rails_test/config/boot.rb",
     "test/rails_test/config/database.yml",
     "test/rails_test/config/environment.rb",
     "test/rails_test/config/environments/development.rb",
     "test/rails_test/config/environments/production.rb",
     "test/rails_test/config/environments/test.rb",
     "test/rails_test/config/initializers/backtrace_silencers.rb",
     "test/rails_test/config/initializers/cms_lite.rb",
     "test/rails_test/config/initializers/inflections.rb",
     "test/rails_test/config/initializers/mime_types.rb",
     "test/rails_test/config/initializers/secret_token.rb",
     "test/rails_test/config/initializers/session_store.rb",
     "test/rails_test/config/routes.rb",
     "test/rails_test/content/pages/en/default/root.html.erb",
     "test/rails_test/content/pages/en/demo/hi.html.erb",
     "test/rails_test/content/pages/en/open/hello.html.erb",
     "test/rails_test/content/protected-pages/en/demo/hi.html.erb",
     "test/rails_test/content/protected-pages/en/protected/safe-hello.html.erb",
     "test/rails_test/db/.keep",
     "test/rails_test/db/migrate/20090320174818_create_muck_permissions_and_roles.rb",
     "test/rails_test/db/migrate/20090402234137_create_languages.rb",
     "test/rails_test/db/migrate/20090426041056_create_countries.rb",
     "test/rails_test/db/migrate/20090426041103_create_states.rb",
     "test/rails_test/db/migrate/20090530170040_create_themes.rb",
     "test/rails_test/db/migrate/20090602041838_create_users.rb",
     "test/rails_test/db/migrate/20090606153236_create_domain_themes.rb",
     "test/rails_test/features/step_definitions/cms_steps.rb",
     "test/rails_test/features/step_definitions/common_steps.rb",
     "test/rails_test/features/step_definitions/webrat_steps.rb",
     "test/rails_test/features/support/env.rb",
     "test/rails_test/features/view_cms_pages.feature",
     "test/rails_test/public/.htaccess",
     "test/rails_test/public/404.html",
     "test/rails_test/public/422.html",
     "test/rails_test/public/500.html",
     "test/rails_test/public/dispatch.rb",
     "test/rails_test/public/favicon.ico",
     "test/rails_test/public/images/rails.png",
     "test/rails_test/public/javascripts/application.js",
     "test/rails_test/public/javascripts/controls.js",
     "test/rails_test/public/javascripts/dragdrop.js",
     "test/rails_test/public/javascripts/effects.js",
     "test/rails_test/public/javascripts/prototype.js",
     "test/rails_test/public/javascripts/rails.js",
     "test/rails_test/public/robots.txt",
     "test/rails_test/public/stylesheets/.gitkeep",
     "test/rails_test/public/stylesheets/application.css",
     "test/rails_test/script/rails",
     "test/rails_test/test/factories.rb",
     "test/rails_test/test/functional/.keep",
     "test/rails_test/test/functional/cms_lite_controller_test.rb",
     "test/rails_test/test/shoulda_macros/controller.rb",
     "test/rails_test/test/shoulda_macros/models.rb",
     "test/rails_test/test/test_helper.rb",
     "test/rails_test/test/unit/.keep",
     "test/rails_test/test/unit/cms_lite_test.rb",
     "test/rails_test/vendor/plugins/ssl_requirement/README",
     "test/rails_test/vendor/plugins/ssl_requirement/lib/ssl_requirement.rb",
     "test/rails_test/vendor/plugins/ssl_requirement/test/ssl_requirement_test.rb"
  ]
  s.homepage = %q{http://github.com/jbasdf/cms_lite}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{cms-lite}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple CMS system}
  s.test_files = [
    "test/rails_test/app/controllers/application_controller.rb",
     "test/rails_test/app/models/user.rb",
     "test/rails_test/app/models/user_session.rb",
     "test/rails_test/config/application.rb",
     "test/rails_test/config/boot.rb",
     "test/rails_test/config/environment.rb",
     "test/rails_test/config/environments/development.rb",
     "test/rails_test/config/environments/production.rb",
     "test/rails_test/config/environments/test.rb",
     "test/rails_test/config/initializers/backtrace_silencers.rb",
     "test/rails_test/config/initializers/cms_lite.rb",
     "test/rails_test/config/initializers/inflections.rb",
     "test/rails_test/config/initializers/mime_types.rb",
     "test/rails_test/config/initializers/secret_token.rb",
     "test/rails_test/config/initializers/session_store.rb",
     "test/rails_test/config/routes.rb",
     "test/rails_test/db/migrate/20090320174818_create_muck_permissions_and_roles.rb",
     "test/rails_test/db/migrate/20090402234137_create_languages.rb",
     "test/rails_test/db/migrate/20090426041056_create_countries.rb",
     "test/rails_test/db/migrate/20090426041103_create_states.rb",
     "test/rails_test/db/migrate/20090530170040_create_themes.rb",
     "test/rails_test/db/migrate/20090602041838_create_users.rb",
     "test/rails_test/db/migrate/20090606153236_create_domain_themes.rb",
     "test/rails_test/features/step_definitions/cms_steps.rb",
     "test/rails_test/features/step_definitions/common_steps.rb",
     "test/rails_test/features/step_definitions/webrat_steps.rb",
     "test/rails_test/features/support/env.rb",
     "test/rails_test/public/dispatch.rb",
     "test/rails_test/test/factories.rb",
     "test/rails_test/test/functional/cms_lite_controller_test.rb",
     "test/rails_test/test/shoulda_macros/controller.rb",
     "test/rails_test/test/shoulda_macros/models.rb",
     "test/rails_test/test/test_helper.rb",
     "test/rails_test/test/unit/cms_lite_test.rb",
     "test/rails_test/vendor/plugins/ssl_requirement/lib/ssl_requirement.rb",
     "test/rails_test/vendor/plugins/ssl_requirement/test/ssl_requirement_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<babelphish>, [">= 0"])
    else
      s.add_dependency(%q<babelphish>, [">= 0"])
    end
  else
    s.add_dependency(%q<babelphish>, [">= 0"])
  end
end

